### ISSUE TITLE
⚠️ Build is failing on Travis [assigned to danielbayerlein]

### ISSUE THREAD

**Issue by bootstraponline** [instructure/paul_bunyan#3]
## 🎃💻 Hacktoberfest

Sign up to [hacktoberfest](https://hacktoberfest.digitalocean.com/) to earn a T-Shirt 👕.

## 🎯 Goal

Submit a pull request that fixes the build on Travis. Currently [the build is failing](https://travis-ci.org/instructure/paul_bunyan/builds/164632167)

**Comment by danielbayerlein** [comment]
I'll fix this issue.

**Comment by bootstraponline** [comment]
Cool. I'll assign this issue to you then so no one else can claim it.

**Comment by bootstraponline** [comment]
Fixed by https://github.com/instructure/paul_bunyan/issues/11
