### ISSUE TITLE
🎃💻 Add Gemnasium badge to README.md

### ISSUE THREAD

**Issue by bootstraponline** [instructure/paul_bunyan#8]
## 🎃💻 Hacktoberfest

Sign up to [hacktoberfest](https://hacktoberfest.digitalocean.com/) to earn a T-Shirt 👕.

## 🎯 Goal

Submit a pull request that adds a Gemnasium badge to the readme. It must be after the other badges, not above the header.

> \[!\[Dependency Status](https://gemnasium.com/badges/github.com/instructure/paul_bunyan.svg)](https://gemnasium.com/github.com/instructure/paul_bunyan)

**Comment by zakaye** [comment]
Might I have a try :>

**Comment by bootstraponline** [comment]
@zakaye This issue has already been fixed by https://github.com/instructure/paul_bunyan/issues/9.
